FROM peter/ssh:latest
MAINTAINER Bryzgalov Peter @ AICS RIKEN
RUN wget https://iperf.fr/download/iperf_2.0.5/iperf_2.0.5-2_amd64
RUN chmod +x iperf_2.0.5-2_amd64 
RUN mv iperf_2.0.5-2_amd64 /usr/bin/iperf
